apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarqube
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: "/mnt/data/sonarqube"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarqube-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: "/mnt/data/sonarqube-db"
